// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhGRSiwzopj3nxXhnszAjdZq-NIL0j4Z4',
    appId: '1:61009781591:web:1e34d504190afcc14c9412',
    messagingSenderId: '61009781591',
    projectId: 'brogam-6b2d9',
    authDomain: 'brogam-6b2d9.firebaseapp.com',
    storageBucket: 'brogam-6b2d9.firebasestorage.app',
    measurementId: 'G-SRMZY5EX08',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyQ4daN5iYjxVbBkzFYq9ZfcwwoUwRlm4',
    appId: '1:61009781591:android:cdba08096c469c544c9412',
    messagingSenderId: '61009781591',
    projectId: 'brogam-6b2d9',
    storageBucket: 'brogam-6b2d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBidfhnSEx72OCX_UFgmDJMR7B6pM6Vhpg',
    appId: '1:61009781591:ios:28b33b758196a7044c9412',
    messagingSenderId: '61009781591',
    projectId: 'brogam-6b2d9',
    storageBucket: 'brogam-6b2d9.firebasestorage.app',
    iosBundleId: 'com.example.brogam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBidfhnSEx72OCX_UFgmDJMR7B6pM6Vhpg',
    appId: '1:61009781591:ios:28b33b758196a7044c9412',
    messagingSenderId: '61009781591',
    projectId: 'brogam-6b2d9',
    storageBucket: 'brogam-6b2d9.firebasestorage.app',
    iosBundleId: 'com.example.brogam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhGRSiwzopj3nxXhnszAjdZq-NIL0j4Z4',
    appId: '1:61009781591:web:b22375450416f3d24c9412',
    messagingSenderId: '61009781591',
    projectId: 'brogam-6b2d9',
    authDomain: 'brogam-6b2d9.firebaseapp.com',
    storageBucket: 'brogam-6b2d9.firebasestorage.app',
    measurementId: 'G-M4QZ8BR74T',
  );
}
